export const chatErrorCodes = {
  SESSION_NOT_FOUND: "CHAT_SESSION_NOT_FOUND",
  MESSAGE_NOT_FOUND: "CHAT_MESSAGE_NOT_FOUND",
  INVALID_CURSOR: "CHAT_INVALID_CURSOR",
  STREAM_NOT_READY: "CHAT_STREAM_NOT_READY",
  MISSING_MESSAGE_ID: "CHAT_MISSING_MESSAGE_ID",
} as const;
