export const aiErrorCodes = {
  AI_TIMEOUT: "CHAT_AI_TIMEOUT",
  AI_MALFORMED_RESPONSE: "CHAT_AI_MALFORMED_RESPONSE",
  AI_RATE_LIMITED: "CHAT_AI_RATE_LIMITED",
  AI_ERROR: "CHAT_AI_ERROR",
} as const;
