export const alarmErrorCodes = {
  NOT_FOUND: "ALARM_NOT_FOUND",
  INVALID_CONDITION: "ALARM_INVALID_CONDITION",
  FORBIDDEN: "ALARM_FORBIDDEN",
  FEEDBACK_NOT_FOUND: "ALARM_FEEDBACK_NOT_FOUND",
} as const;
